// src/components/Colorpicker.tsx
import { useEffect, useRef } from "react";
import { useColorsStore } from "../colors.store";

type PickerProps = {
  index: number;
  color: string;
  isFocused?: boolean;
};

const Picker = ({ index, color, isFocused }: PickerProps) => {
  const { setColor } = useColorsStore();
  const ref = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (isFocused) {
      ref.current?.click();
    }
  });

  return (
    <div className="relative mx-auto my-auto">
      <input
        ref={ref}
        type="color"
        value={color}
        onChange={(e) => setColor(index, e.target.value)}
        className="w-12 h-12 cursor-pointer transition-colors"
        style={{ backgroundColor: color }}
      />
    </div>
  );
};

type ColorPickerProps = {
  currentFocus?: number | null;
};

export function ColorPicker({ currentFocus }: ColorPickerProps) {
  const { colors } = useColorsStore();

  return (
    <div className="mb-8">
      <h2 className="text-lg font-semibold mb-4 text-gray-800">
        Color Palette
      </h2>
      <div className="grid grid-cols-8 gap-4 p-4 pb-8 bg-gray-50 rounded-lg">
        {colors.map((color, index) => (
          <Picker
            key={index}
            index={index}
            color={color}
            isFocused={currentFocus === index}
          />
        ))}
      </div>
      {Boolean(currentFocus) && (
        <p className="text-sm text-gray-600 mt-2">
          Selected: Color {currentFocus! + 1} ({colors[currentFocus!]})
        </p>
      )}
    </div>
  );
}

// src/lib/components/ColorPicker.svelte
<script lang="ts">
	import ColorInput from './ColorInput.svelte';

	interface Props {
		colors: string[];
		currentFocus?: number | null;
	}

	let { colors = $bindable(), currentFocus = null }: Props = $props();

	function handleColorChange(index: number, event: Event) {
		const target = event.target as HTMLInputElement;
		colors[index] = target.value;
	}

	function openColorPicker(index: number) {
		const input = document.getElementById(`color-${index}`) as HTMLInputElement;
		input?.click();
	}

	$effect(() => {
		if (currentFocus !== null) {
			setTimeout(() => {
				openColorPicker(currentFocus);
			}, 100);
		}
	});
</script>

<div class="rounded-xl bg-white p-6 border border-gray-200">
	<div class="mb-6">
		<h3 class="text-xl font-semibold text-gray-900">Color Palette</h3>
		<p class="mt-1 text-sm text-gray-500">Click on the logo or select colors below</p>
	</div>
	<div class="grid grid-cols-4 gap-3">
		{#each colors as color, index}
			<ColorInput {index} {color} {currentFocus} onColorChange={handleColorChange} />
		{/each}
	</div>
</div>
